### ISSUE TITLE
大佬还请教一个问题，http不支持拖动播放这个能解决吗

### ISSUE THREAD

**Issue by Yang0630** [talver/SuperVideo#4]
视频只能从头开始播放，或者视频完全加载完毕后可以拖动播放。体验有点不好，能改成可以拖动播放实时加载吗

**Comment by sunraiseyx** [comment]
> 视频只能从头开始播放，或者视频完全加载完毕后可以拖动播放。体验有点不好，能改成可以拖动播放实时加载吗

请问您是怎么做到这一步的吗？我这边需要学习下楼主的项目，但加密后成功了打不开原始的加密视频。即解密不可行。另楼主说的程序中自带的web服务器我不是很理解。

**Comment by Yang0630** [comment]
你没看源码吗？里面有个http监听实现了一个类型iis的web 服务端

**Comment by Yang0630** [comment]
> > 视频只能从头开始播放，或者视频完全加载完毕后可以拖动播放。体验有点不好，能改成可以拖动播放实时加载吗
> 
> 请问您是怎么做到这一步的吗？我这边需要学习下楼主的项目，但加密后成功了打不开原始的加密视频。即解密不可行。另楼主说的程序中自带的web服务器我不是很理解。

 httpListener

**Comment by sunraiseyx** [comment]
您好！谢谢您的及时回复！抱歉我才下载楼主的代码没多久，故没怎么细看楼主的项目源码。刚刚发现有个语句：frm.Url = string.Format("http://localhost:18888/?file={0}&amp;token={1}&amp;category={2}", filename, Token, category);不知道是不是您所说的关键点。我下载好楼主的项目即把dll文件重新导入了之后，发现有点小异常，之后重新运行，发现可以加密了。但加密视频照理说应该是在主界面上出现的。但没有出现，所以我很奇怪。点击的时候好像有点小bug。运行环境新装的，Visual Studio2019.具体情况就是这样。请问你有时间吗？我是个电子专业的研究生，.Net不是特别熟悉，略知道皮毛。我现在就想把它完整运行起来，还望您指导下。这个楼主的项目可能在某些方面可以指导我一点。源码我可以自己慢慢研究琢磨，不需要您花时间的。谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yang0630"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 下午5:44
收件人:&nbsp;"talver/SuperVideo"<SuperVideo@noreply.github.com&gt;;
抄送:&nbsp;"江上游"<sunraiseyx@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [talver/SuperVideo] 大佬还请教一个问题，http不支持拖动播放这个能解决吗 (#4)





 
你没看源码吗？里面有个http监听实现了一个类型iis的web 服务端
