### ISSUE TITLE
想问下加密的话，可以把key写进加密文件吗？

### ISSUE THREAD

**Issue by lawwing** [talver/SuperVideo#6]
同时把加密的key，需要加密的部分放进去文件头，然后普通的设备破解不了

**Comment by talver** [comment]
C#本身容易被破解，建议你不要将key写入文件，










在 2021-03-30 09:41:47，"lawwing" ***@***.***> 写道：

同时把加密的key，需要加密的部分放进去文件头，然后普通的设备破解不了

**Comment by lawwing** [comment]
我是写进视频文件里面

**Comment by talver** [comment]
你要是想做找回密码功能是可以将key写入视频文件，这样做对用户来讲就是一个严重的后门，违背了加密的初衷，我希望是谁加密谁解密，更多的保护用户隐私。
